ConsulProfilesActive = 'docker;go'
ReadLimit = 100
ConsulPort = 8500
ServiceTimeout = 5000
CheckInterval = '10s'
ServiceAddress = 'edgex-core-command'
ServicePort = 48082
DeviceServiceProtocol = 'http'
AppOpenMsg = 'This is the Core Command Micro Service'
URLProtocol = 'http://'
URLDevicePath = '/api/v1/device'
ConsulHost = 'edgex-core-consul'
ConsulCheckAddress = 'http://edgex-core-command:48082/api/v1/ping'
EnableRemoteLogging = true
LogFile = './logs/edgex-core-command.log'
LoggingRemoteURL = 'http://edgex-support-logging:48061/api/v1/logs'
MetaAddressableURL = 'http://edgex-core-metadata:48081/api/v1/addressable'
MetaAddressablePath = '/api/v1/addressable'
MetaDeviceServiceURL = 'http://edgex-core-metadata:48081/api/v1/deviceservice'
MetaDeviceServicePath = '/api/v1/deviceservice'
MetaDeviceProfileURL = 'http://edgex-core-metadata:48081/api/v1/deviceprofile'
MetaDeviceProfilePath = '/api/v1/deviceprofile'
MetaDeviceURL = 'http://edgex-core-metadata:48081/api/v1/device'
MetaDevicePath = '/api/v1/device'
MetaDeviceReportURL = 'http://edgex-core-metadata:48081/api/v1/devicereport'
MetaDeviceReportPath = '/api/v1/devicereport'
MetaCommandURL = 'http://edgex-core-metadata:48081/api/v1/command'
MetaCommandPath = '/api/v1/command'
MetaEventURL = 'http://edgex-core-metadata:48081/api/v1/event'
MetaEventPath = '/api/v1/event'
MetaScheduleURL = 'http://edgex-core-metadata:48081/api/v1/schedule'
MetaSchedulePath = '/api/v1/schedule'
MetaProvisionWatcherURL = 'http://edgex-core-metadata:48081/api/v1/provisionwatcher'
MetaProvisionWatcherPath = '/api/v1/provisionwatcher'

