#################################################################################
# Copyright 2019 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#
# @author: Tingyu Zeng, Dell
#################################################################################

# This is a TOML config file for edgexsecurity service.

[Writable]
LogLevel = "DEBUG"
RequestTimeout = 10

[Logging]
EnableRemote = false
File = "./logs/security-proxy-setup.log"

[KongURL]
Server = "kong"
AdminPort = 8001
AdminPortSSL = 8444
ApplicationPort = 8000
ApplicationPortSSL = 8443

[KongAuth]
Name = "jwt"
TokenTTL = 0
Resource = "coredata"
OutputPath = "accessToken.json"

[KongACL]
Name = "acl"
WhiteList = "admin"

[SecretService]
Server = "edgex-vault"
Port = 8200
HealthCheckPath = "v1/sys/health"
CertPath = "/v1/secret/edgex/edgex-security-proxy-setup/"
TokenPath = "/tmp/edgex/secrets/edgex-security-proxy-setup/secrets-token.json"
CACertPath = "/tmp/edgex/secrets/ca/ca.pem"
SNIS = ["edgex-kong"]

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080

  [Clients.Metadata]
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081

  [Clients.Command]
  Protocol = "http"
  Host = "edgex-core-command"
  Port = 48082

  [Clients.Notifications]
  Protocol = "http"
  Host = "edgex-support-notifications"
  Port = 48060

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

  [Clients.Scheduler]
  Protocol = "http"
  Host = "edgex-support-scheduler"
  Port = 48085

  [Clients.RulesEngine]
  Protocol = "http"
  Host = "edgex-support-rulesengine"
  Port = 48075

  [Clients.VirtualDevice]
  Protocol = "http"
  Host = "edgex-device-virtual"
  Port = 49990

[Startup]
Duration = 30
Interval = 1