[Writable]
ScheduleIntervalTime = 500
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-support-scheduler'
Port = 48085
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = true
File = '/edgex/logs/edgex-support-scheduler.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'edgex-support-logging'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'edgex-mongo'
  Name = 'scheduler'
  Password = 'password'
  Port = 27017
  Username = 'scheduler'
  Timeout = 5000
  Type = 'mongodb'

[Intervals]
    [Intervals.Midnight]
    Name = 'midnight'
    Start = '20180101T000000'
    Frequency = '24h'

[IntervalActions]
    [IntervalActions.ScrubPushed]
    Name = 'scrub-pushed-events'
    Host = 'edgex-core-data'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Target = 'core-data'
    Path = '/api/v1/event/scrub'
    Interval = 'midnight'

    [IntervalActions.ScrubAged]
    Name = 'scrub-aged-events'
    Host = 'edgex-core-data'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Target = 'core-data'
    Path = '/api/v1/event/removeold/age/604800000'
    Interval = 'midnight'

[SecretStore]
Host = 'edgex-vault'
Port = 8200
Path = '/v1/secret/edgex/scheduler/'
Protocol = 'https'
RootCaCertPath = '/tmp/edgex/secrets/ca/ca.pem'
ServerName = 'edgex-vault'
TokenFile = '/tmp/edgex/secrets/edgex-support-scheduler/secrets-token.json'
# Number of attemtps to retry retrieving secrets before failing to start the service.
AdditionalRetryAttempts = 10
# Amount of time to wait before attempting another retry
RetryWaitPeriod = "1s"
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

[Startup]
Duration = 30
Interval = 1
