[Writable]
ResendLimit = 2
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-support-notifications'
Port = 48060
Protocol = 'http'
MaxResultCount = 500000
StartupMsg = 'This is the Support Notifications Microservice'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = true
File = '/edgex/logs/edgex-support-notifications.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'edgex-support-logging'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'edgex-mongo'
  Name = 'notifications'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[Smtp]
  Host = 'smtp.gmail.com'
  Username = 'username@mail.example.com'
  Password = ''
  Port = 587
  Sender = 'jdoe@gmail.com'
  EnableSelfSignedCert = false
  Subject = 'EdgeX Notification'

[SecretStore]
Host = 'edgex-vault'
Port = 8200
Path = '/v1/secret/edgex/supportnotifications/'
Protocol = 'http'
RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
ServerName = 'edgex-vault'
TokenFile = '/vault/config/assets/resp-init.json'
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

[Startup]
Duration = 30
Interval = 1
