#################################################################################
# Copyright 2019 Dell Inc.
# Copyright 2020 Intel Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#
#################################################################################

# This is a TOML config file for EdgeX security-secretstore-setup service.

LogLevel = 'DEBUG'

[SecretStore]
Type = "vault"
Protocol = "http"
Host = "edgex-vault"
Port = 8200
CertPath = ""
CaFilePath = ""
CertFilePath = ""
KeyFilePath = ""
TokenFolderPath = "/vault/config/assets"
TokenFile = "resp-init.json"
VaultSecretShares = 5
VaultSecretThreshold = 3
TokenProvider = "/security-file-token-provider"
TokenProviderArgs = [ "-confdir", "res-file-token-provider" ]
TokenProviderType = "oneshot"
TokenProviderAdminTokenPath = "/run/edgex/secrets/tokenprovider/secrets-token.json"
PasswordProvider = ""
PasswordProviderArgs = [ ]
RevokeRootTokens = true
ConsulSecretsAdminTokenPath = "/tmp/edgex/secrets/edgex-consul/admin/token.json"

[Databases]
  [Databases.admin]
  Username = "admin"

  [Databases.authorization]
  Username = "admin"

  [Databases.config]
  Username = "admin"

  [Databases.local]
  Username = "admin"

  [Databases.metadata]
  Service = "metadata"
  Username = "meta"

  [Databases.coredata]
  Service = "coredata"
  Username = "core"

  [Databases.rulesengine]
  Service = "rulesengine"
  Username = "rulesengine"

  [Databases.notifications]
  Service = "notifications"
  Username = "notifications"

  [Databases.scheduler]
  Service = "scheduler"
  Username = "scheduler"

  [Databases.application-service]
  Service = "appservice"
  Username = "appservice"

