Hostname = 'edgex-export-distro'
Port = 48070
DistroHost = 'edgex-export-distro'
ClientHost = 'edgex-export-client'
DataHost = 'edgex-core-data'
MQTTSCert = 'dummy.crt'
MQTTSKey = 'dummy.key'
AWSCert = 'dummy.crt'
AWSKey = 'dummy.key'
ConsulHost = 'edgex-core-consul'
ConsulPort = 8500
ConsulProfilesActive = 'docker'
CheckInterval = '10s'
MarkPushed = false
