Hostname = '127.0.0.1'
Port = 48070
Timeout = 5000
DistroHost = '127.0.0.1'
ClientHost = '127.0.0.1'
DataHost = '127.0.0.1'
DataPort = 48080
MQTTSCert = 'dummy.crt'
MQTTSKey = 'dummy.key'
AWSCert = 'dummy.crt'
AWSKey = 'dummy.key'
ConsulHost = 'localhost'
ConsulPort = 8500
ConsulProfilesActive = 'go'
CheckInterval = '10s'
MarkPushed = false
EnableRemoteLogging = false
LoggingFile = './logs/edgex-export-distro.log'
LoggingRemoteURL = 'http://localhost:48061/api/v1/logs'
AppOpenMsg = 'This is the Export Distro Microservice'
