ApplicationName = 'edgex-export-client'
Hostname = 'edgex-export-client'
Port = 48071
DBType = 'mongodb'
MongoURL = 'edgex-mongo'
MongoUsername = ''
MongoPassword = ''
MongoDatabase = 'exportclient'
MongoPort = 27017
MongoConnectTimeout = 5000
MongoSocketTimeout = 5000
ConsulHost = 'edgex-core-consul'
ConsulPort = 8500
CheckInterval = '10s'
ConsulProfilesActive = 'docker;go'
ClientHost = 'edgex-export-client'
DistroHost = 'edgex-export-distro'
DistroPort = 48070
