ApplicationName = 'edgex-export-client'
Hostname = 'edgex-export-client'
Port = 48071
DBType = 'mongodb'
MongoURL = 'edgex-mongo'
MongoUsername = 'export'
MongoPassword = 'password'
MongoDatabase = 'exportclient'
MongoPort = 27017
MongoConnectTimeout = 5000
MongoSocketTimeout = 5000
ConsulHost ='edgex-export-consul'
ConsulPort = 8500
CheckInterval = '10s'
ConsulProfilesActive = 'docker;go'
ClientHost = 'EXPORT_CLIENT_HOST'
DistroHost = 'EXPORT_CLIENT_DISTRO_HOST'
DistroPort = 48070