Hostname = '127.0.0.1'
Port = 48071
Timeout = 50000
DBType = 'mongodb'
MongoURL = '0.0.0.0'
MongoUsername = ''
MongoPassword = ''
MongoDatabaseName = 'exportclient'
MongoPort = 27017
MongoConnectTimeout = 5000
MongoSocketTimeout = 5000
ConsulHost = 'localhost'
ConsulPort = 8500
CheckInterval = '10s'
ConsulProfilesActive = 'go'
DistroHost = 'localhost'
DistroPort = 48070
EnableRemoteLogging = false
LoggingFile = './logs/edgex-export-client.log'
LoggingRemoteURL = 'http://localhost:48061/api/v1/logs'
AppOpenMsg = 'This is the Export Client Microservice'
