ApplicationName = 'export-client'
Hostname = '127.0.0.1'
Port = 48071
DBType = 'mongodb'
MongoURL = '0.0.0.0'
MongoUsername = ''
MongoPassword = ''
MongoDatabase = 'coredata'
MongoPort = 27017
MongoConnectTimeout = 5000
MongoSocketTimeout = 5000
ConsulHost ='127.0.0.1'
ConsulPort = 8500
CheckInterval = '10s'
ConsulProfilesActive = 'go'
ClientHost = 'EXPORT_CLIENT_HOST'
DistroHost = 'EXPORT_CLIENT_DISTRO_HOST'
DistroPort = 48070