Hostname = 'edgex-export-client'
Port = 48071
Timeout = 50000
DBType = 'mongodb'
MongoURL = 'edgex-mongo'
MongoUsername = ''
MongoPassword = ''
MongoDatabaseName = 'exportclient'
MongoPort = 27017
MongoConnectTimeout = 5000
MongoSocketTimeout = 5000
ConsulHost = 'edgex-core-consul'
ConsulPort = 8500
CheckInterval = '10s'
ConsulProfilesActive = 'docker'
DistroHost = 'edgex-export-distro'
DistroPort = 48070
EnableRemoteLogging = false
LoggingFile = './logs/edgex-export-client.log'
LoggingRemoteURL = 'http://localhost:48061/api/v1/logs'
AppOpenMsg = 'This is the Export Client Microservice'
