# This TOML file now incorporates a now-defunct manifest file, which had specified the services managed by the SMA.
# The SMA needs the details provided in this TOML to stop/start/restart each service that the SMA manages.
# What about specifying the edgexsecurity service to use?
# Different versions of this manifest may exist depending on how/where EdgeX is deployed (Docker v. Snappy, Windows v. Linux, etc.).
# In the first release of the SMA, the manifest will be static.
# In the future, the manifest may be more dynamic or even provided by some 3rd party orchestrator.

ExecutorPath = '/sys-mgmt-executor'

# The MetricsMechanism setting can be one of the following options:
MetricsMechanism = 'executor'
# MetricsMechanism = 'direct-service'

[Writable]
ResendLimit = 2
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-sys-mgmt-agent'
Port = 48090
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the System Management Agent Service'
Timeout = 5000
FormatSpecifier = '%(\\d+\\$)?([-#+ 0(\\<]*)?(\\d+)?(\\.\\d+)?([tT])?([a-zA-Z%])'

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = true
File = '/edgex/logs/edgex-sys-mgmt-agent.log'

[Clients]
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'edgex-support-notifications'
  Port = 48060

  [Clients.Command]
  Protocol = 'http'
  Host = 'edgex-core-command'
  Port = 48082

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'edgex-core-metadata'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'edgex-support-logging'
  Port = 48061

  [Clients.CoreData]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

  [Clients.Scheduler]
  Protocol = 'http'
  Host = 'edgex-support-scheduler'
  Port = 48085

  [Clients.Export]
  Protocol = 'http'
  Host = 'edgex-export-client'
  Port = 48071

  [Clients.Distro]
  Protocol = 'http'
  Host = 'edgex-export-distro'
  Port = 48070

[SecretStore]
Host = 'edgex-vault'
Port = 8200
Path = '/v1/secrets/edgex/sys-mgmt-agent/'
Protocol = 'http'
RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
ServerName = 'edgex-vault'
TokenFile = '/vault/config/assets/resp-init.json'
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

[Startup]
Duration = 30
Interval = 1
