[Writable]
LogLevel = 'INFO'

[Logging]
EnableRemote = false
File = './logs/security-secrets-setup.log'

[SecretsSetup]
WorkDir = "/run/edgex/secrets-setup"
DeployDir = "/run/edgex/secrets"
CacheDir = "/etc/edgex/pki"
CertConfigDir = "./res"

[Startup]
Duration = 30
Interval = 1