[Writable]
LogLevel = 'INFO'

# Remote and file logging disabled so only stdout logging is used
[Logging]
EnableRemote = false
File = ''

[SecretsSetup]
WorkDir = "/tmp/edgex/secrets-setup"
DeployDir = "/tmp/edgex/secrets"
CacheDir = "/etc/edgex/pki"
CertConfigDir = "./res"
