[Writable]
LogLevel = 'DEBUG'

[SecretService]
Protocol = "http"
Server = "edgex-vault"
ServerName = ""
Port = 8200
CaFilePath = ""

[TokenFileProvider]
PrivilegedTokenPath = "/run/edgex/secrets/tokenprovider/secrets-token.json"
ConfigFile = "res-file-token-provider/token-config.json"
OutputDir = "/tmp/edgex/secrets"
OutputFilename = "secrets-token.json"
