[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-core-command'
Port = 48082
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Core Command Microservice'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = true
File = '/edgex/logs/edgex-core-command.log'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'edgex-core-metadata'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'edgex-support-logging'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'edgex-mongo'
  Name = 'metadata'
  Password = 'password'
  Port = 27017
  Username = 'meta'
  Timeout = 5000
  Type = 'mongodb'

[SecretStore]
Host = 'edgex-vault'
Port = 8200
# Use the core-meta data secrets due to core-command using core-meta-data's database for persistance.
Path = '/v1/secret/edgex/metadata/'
Protocol = 'https'
RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
ServerName = 'edgex-vault'
TokenFile = '/vault/config/assets/resp-init.json'
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

[Startup]
Duration = 30
Interval = 1
