#################################################################################
# Copyright 2019 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#
# @author: Tingyu Zeng, Dell
#################################################################################

# This is a TOML config file for edgexsecurity service.

[Writable]
LogLevel = "DEBUG"
RequestTimeout = 10

[Logging]
EnableRemote = false
File = "./logs/security-proxy-setup.log"

[KongURL]
Server = "127.0.0.1"
AdminPort = 8001
AdminPortSSL = 8444
ApplicationPort = 8000
ApplicationPortSSL = 8443

[KongAuth]
Name = "jwt"
TokenTTL = 0
Resource = "coredata"
OutputPath = "accessToken.json"

[KongACL]
Name = "acl"
WhiteList = "admin"

[SecretService]
Server = "localhost"
Port = 8200
HealthCheckPath = "v1/sys/health"
CertPath = "secret/edgex/edgex-security-proxy-setup/kong-tls"
TokenPath = "res/resp-init.json"
CACertPath = "res/EdgeXFoundryCA/EdgeXFoundryCA.pem"
SNIS = ["localhost"]

[Clients]
  [Clients.Coredata]
  Protocol = "http"
  Host = "localhost"
  Port = 48080
	
  [Clients.Metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 48081
	
  [Clients.Command]
  Protocol = "http"
  Host = "localhost"
  Port = 48082
	
  [Clients.Notifications]
  Protocol = "http"
  Host = "localhost"
  Port = 48060
		
  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

  [Clients.Distro]
  Protocol = "http"
  Host = "localhost"
  Port = 48070
	
  [Clients.Export]
  Protocol = "http"
  Host = "localhost"
  Port = 48071

  [Clients.Scheduler]
  Protocol = "http"
  Host = "localhost"
  Port = 48085

  [Clients.RulesEngine]
  Protocol = "http"
  Host = "localhost"
  Port = 48075
	
  [Clients.VirtualDevice]
  Protocol = "http"
  Host = "localhost"
  Port = 49990

[Startup]
Duration = 30
Interval = 1