# This TOML file now incorporates a now-defunct manifest file, which had specified the services managed by the SMA.
# The SMA needs the details provided in this TOML to stop/start/restart each service that the SMA manages.
# What about specifying the edgexsecurity service to use?
# Different versions of this manifest may exist depending on how/where EdgeX is deployed (Docker v. Snappy, Windows v. Linux, etc.).
# In the first release of the SMA, the manifest will be static.
# In the future, the manifest may be more dynamic or even provided by some 3rd party orchestrator.

ExecutorPath = '../sys-mgmt-executor/sys-mgmt-executor'

# The MetricsMechanism setting can be one of the following options:
# MetricsMechanism = 'executor'
MetricsMechanism = 'direct-service'

[Writable]
ResendLimit = 2
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48090
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the System Management Agent Service'
Timeout = 20000
FormatSpecifier = '%(\\d+\\$)?([-#+ 0(\\<]*)?(\\d+)?(\\.\\d+)?([tT])?([a-zA-Z%])'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-sys-mgmt-agent.log'

[Clients]
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

  [Clients.Command]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48082

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Scheduler]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48085

[Startup]
Duration = 30
Interval = 1