# This TOML file now incorporates a now-defunct manifest file, which had specified the services managed by the SMA.
# The SMA needs the details provided in this TOML to stop/start/restart each service that the SMA manages.
# What about specifying the edgexsecurity service to use?
# Different versions of this manifest may exist depending on how/where EdgeX is deployed (Docker v. Snappy, Windows v. Linux, etc.).
# In the first release of the SMA, the manifest will be static.
# In the future, the manifest may be more dynamic or even provided by some 3rd party orchestrator.

ApplicationName = 'edgex-sys-mgmt-agent'
RegistryProfilesActive = 'go'
ValidateCheck = false
AppOpenMsg = 'This is the System Management Agent Service'
FormatSpecifier = '%(\\d+\\$)?([-#+ 0(\\<]*)?(\\d+)?(\\.\\d+)?([tT])?([a-zA-Z%])'
ServicePort = 48090
ServiceTimeout = 5000
ServiceAddress = 'localhost'
CheckInterval = '10s'
EnableRemoteLogging = false
LoggingFile = './logs/edgex-sys-mgmt-agent.log'

ExecutorPath = '/path/to/the/file'

[Clients]
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

  [Clients.Command]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48082

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Scheduler]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48085

  [Clients.Export]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48071

  [Clients.Distro]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48070
