ScheduleIntervalTime = 500

[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.DB]
        path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = '' # Leave blank so default to Host value unless different value is needed.
Port = 48085
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'scheduler'
  Port = 6379
  Timeout = 5000
  Type = 'redisdb'

[Intervals]
    [Intervals.Midnight]
    Name = 'midnight'
    Start = '20180101T000000'
    Interval = '24h'

[IntervalActions]
    [IntervalActions.ScrubAged]
    Name = 'scrub-aged-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Target = 'core-data'
    Path = '/api/v2/event/age/604800000000000' # Remove events older than 7 days
    Interval = 'midnight'

[SecretStore]
Type = 'vault'
Protocol = 'http'
Host = 'localhost'
Port = 8200
Path = '/v1/secret/edgex/scheduler/'
TokenFile = '/vault/config/assets/resp-init.json'
RootCaCertPath = ''
ServerName = ''
# Number of attempts to retry retrieving secrets before failing to start the service.
AdditionalRetryAttempts = 10
# Amount of time to wait before attempting another retry
RetryWaitPeriod = "1s"
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

