ScheduleIntervalTime = 500

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48085
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-support-scheduler.log'
Level = 'INFO'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'scheduler'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[Intervals]
    [Intervals.Midnight]
    Name = 'midnight'
    Start = '20180101T000000'
    Frequency = 'P1D'

[IntervalActions]
    [IntervalActions.ScrubPushed]
    Name = 'scrub-pushed-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Target = 'core-data'
    Path = '/api/v1/event/scrub'
    Interval = 'midnight'

    [IntervalActions.ScrubAged]
    Name = 'scrub-aged-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Target = 'core-data'
    Path = '/api/v1/event/removeold/age/604800000'
    Interval = 'midnight'





