[Writable]
ScheduleIntervalTime = 500
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48085
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-support-scheduler.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'scheduler'
  # Temporarily commented out. Will be pulled back in with secure Redis PR.
  # Password = 'password'
  # Username = 'scheduler'
  Password = ''
  Username = ''
  Port = 6379
  Timeout = 5000
  Type = 'redisdb'

[Intervals]
    [Intervals.Midnight]
    Name = 'midnight'
    Start = '20180101T000000'
    Frequency = '24h'

[IntervalActions]
    [IntervalActions.ScrubPushed]
    Name = 'scrub-pushed-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Target = 'core-data'
    Path = '/api/v1/event/scrub'
    Interval = 'midnight'

    [IntervalActions.ScrubAged]
    Name = 'scrub-aged-events'
    Host = 'localhost'
    Port = 48080
    Protocol = 'http'
    Method = 'DELETE'
    Target = 'core-data'
    Path = '/api/v1/event/removeold/age/604800000'
    Interval = 'midnight'

[SecretStore]
Host = 'localhost'
Port = 8200
Path = '/v1/secret/edgex/scheduler/'
Protocol = 'https'
RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
ServerName = 'localhost'
TokenFile = '/vault/config/assets/resp-init.json'
# Number of attemtps to retry retrieving secrets before failing to start the service.
AdditionalRetryAttempts = 10
# Amount of time to wait before attempting another retry
RetryWaitPeriod = "1s"
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
  AuthToken = 'edgex'

[Startup]
Duration = 30
Interval = 1
