ConfigPath = './config'
GlobalPrefix = 'config'
ConsulProtocol = 'http'
ConsulHost = 'localhost'
ConsulPort = 8500
IsReset = true
FailLimit = 30
FailWaitTime = 3
AcceptablePropertyExtensions = ['.toml','.yaml', '.yml', '.properties']
YamlExtensions = ['.yaml','.yml']
TomlExtensions = ['.toml']
EnableRemoteLogging = false
LoggingFile = './logs/edgex-config-seed.log'
LoggingRemoteURL = 'http://localhost:48061/api/v1/logs'
