[Writable]
ResendLimit = 2
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48060
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the Support Notifications Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-support-notifications.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'notifications'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[Smtp]
Host = 'smtp.gmail.com'
Password = 'mypassword'
Port = 587
Sender = 'jdoe@gmail.com'
Subject = 'EdgeX Notification'



