Writable:
  LogLevel: INFO
  ResendLimit: 2
  ResendInterval: 5s
  InsecureSecrets:
    SMTP:
      SecretName: smtp
      SecretData:
        username: username@mail.example.com
        password: ''
Service:
  Host: localhost
  Port: 59860
  StartupMsg: "This is the Support Notifications Microservice"
  SecurityOptions:
    Mode: "zerotrust"
    OpenZitiController: "openziti:1280"
    OpenZitiServiceName: "edgex.support-notifications"
Smtp:
  Host: my.email.server
  Port: 587
  Sender: some.email.address
  EnableSelfSignedCert: false
  Subject: EdgeX Notification
  # SecretName is used to specify the secret name to store the credential(username and password) for connecting the SMTP server
  # User need to store the credential via the /secret API before sending the email notification
  SecretName: smtp
  # AuthMode is the SMTP authentication mechanism. Currently, "usernamepassword" is the only AuthMode supported by this service, and the secret keys are "username" and "password".
  AuthMode: usernamepassword

MessageBus:
  Optional:
    ClientId: support-notifications

Database:
  Name: notifications

Retention:
  Enabled: false
  Interval: 30m    # Purging interval defines when the database should be rid of notifications above the high watermark.
  MaxCap: 5000     # The maximum capacity defines where the high watermark of notifications should be detected for purging the amount of the notifications to the minimum capacity.
  MinCap: 4000     # The minimum capacity defines where the total count of notifications should be returned to during purging.
