[Writable]
ResendLimit = 2
ResendInterval = "5s"
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.SMTP]
    path = "smtp"
      [Writable.InsecureSecrets.SMTP.Secrets]
      username = "username@mail.example.com"
      password = ""

[Service]
Port = 59860
StartupMsg = "This is the Support Notifications Microservice"

[Database]
Name = "notifications"

[Smtp]
  Host = "smtp.gmail.com"
  Port = 587
  Sender = "jdoe@gmail.com"
  EnableSelfSignedCert = false
  Subject = "EdgeX Notification"
  # SecretPath is used to specify the secret path to store the credential(username and password) for connecting the SMTP server
  # User need to store the credential via the /secret API before sending the email notification
  SecretPath = "smtp"
  # AuthMode is the SMTP authentication mechanism. Currently, "usernamepassword" is the only AuthMode supported by this service, and the secret keys are "username" and "password".
  AuthMode = "usernamepassword"

[MessageBus]
  [MessageBus.Topics]
  # No topic yet. Metrics topic is handled in [Writable.Telemetry] above
  [MessageBus.Optional]
  # Default MQTT Specific options that need to be here to enable evnironment variable overrides of them
  ClientId ="support-notifications"