Writable:
  LogLevel: INFO
  ProfileChange:
    StrictDeviceProfileChanges: false
    StrictDeviceProfileDeletes: false
  UoM:
    Validation: false
Service:
  Host: localhost
  Port: 59881
  StartupMsg: "This is the EdgeX Core Metadata Microservice"
  SecurityOptions:
    Mode: "zerotrust"
    OpenZitiController: "openziti:1280"
    OpenZitiServiceName: "edgex.core-metadata"

UoM:
  UoMFile: ./res/uom.yaml

MessageBus:
  Optional:
    ClientId: core-metadata

Database:
  Name: metadata

