DBType = 'mongodb'
MongoDatabaseName = 'metadata'
MongoDBUserName = ''
MongoDBPassword = ''
MongoDBHost = 'localhost'
MongoDBPort = 27017
MongoDBConnectTimeout = 5000
ReadMaxLimit = 100
Protocol = 'http'
ServiceAddress = 'localhost'
ServicePort = 48081
ServiceTimeout = 5000
AppOpenMsg = 'This is the EdgeX Core Metadata MicroService'
ConsulHost = 'localhost'
ConsulProfilesActive = 'go'
ConsulCheckAddress = 'http://localhost:48081/api/v1/ping'
CheckInterval = '10s'
ConsulPort = 8500
EnableRemoteLogging = false
LoggingFile = './logs/edgex-core-metadata.log'
LoggingRemoteURL = 'http://localhost:48061/api/v1/logs'
NotificationPostDeviceChanges = true
NotificationsSlug = 'device-change-'
NotificationContent = 'Device update: '
NotificationSender = 'core-metadata'
NotificationDescription = 'Metadata device notice'
NotificationLabel = 'metadata'
SupportNotificationsHost = 'localhost'
SupportNotificationsPort = 48060
SupportNotificationsNotificationURL = 'http://localhost:48060/api/v1/notification'
SupportNotificationsSubscriptionURL = 'http://localhost:48060/api/v1/subscription'
SupportNotificationsTransmissionURL = 'http://localhost:48060/api/v1/transmission'
