[Writable]
LogLevel = 'INFO'
EnableValueDescriptorManagement = false

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48081
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the EdgeX Core Metadata Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-core-metadata.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080


[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'metadata'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[Notifications]
PostDeviceChanges = true
Slug = 'device-change-'
Content = 'Device update: '
Sender = 'core-metadata'
Description = 'Metadata device notice'
Label = 'metadata'

[SecretStore]
Host = 'localhost'
Port = 8200
Path = '/v1/secret/edgex/metadata/'
Protocol = 'https'
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
  AuthToken = 'edgex'

[Startup]
Duration = 30
Interval = 1
