[Writable]
LogLevel = 'INFO'
EnableValueDescriptorManagement = false
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 59881
ServerBindAddr = '' # Leave blank so default to Host value unless different value is needed.
StartupMsg = 'This is the EdgeX Core Metadata Microservice'
MaxResultCount = 50000
MaxRequestSize = 0 # Not curently used.
RequestTimeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.support-notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 59860

  [Clients.core-data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 59880

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'metadata'
  Password = 'password'
  Username = 'meta'
  Port = 6379
  Timeout = 5000
  Type = 'redisdb'

[Notifications]
PostDeviceChanges = true
Slug = 'device-change-'
Content = 'Device update: '
Sender = 'core-metadata'
Description = 'Metadata device notice'
Label = 'metadata'

[SecretStore]
Type = 'vault'
Protocol = 'http'
Host = 'localhost'
Port = 8200
Path = '/v1/secret/edgex/core-metadata/'
TokenFile = '/tmp/edgex/secrets/core-metadata/secrets-token.json'
RootCaCertPath = ''
ServerName = ''
# Number of attempts to retry retrieving secrets before failing to start the service.
AdditionalRetryAttempts = 10
# Amount of time to wait before attempting another retry
RetryWaitPeriod = "1s"
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

