[Writable]
DeviceUpdateLastConnected = false
MetaDataCheck = false
PersistData = true
ServiceUpdateLastConnected = false
ValidateCheck = false
LogLevel = 'INFO'
ChecksumAlgo = 'xxHash'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
Port = 48080
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Core Data Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

# Remote and file logging disabled so only stdout logging is used
[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'coredata'
  Password = 'password'
  Username = 'core'
  Port = 6379
  Timeout = 5000
  Type = 'redisdb'

[MessageQueue]
Protocol = 'tcp'
Host = '*'
Port = 5563
Type = 'zero'
Topic = 'events'
[MessageQueue.Optional]
    # Default MQTT Specific options that need to be here to enable evnironment variable overrides of them
    # Client Identifiers
    Username =""
    Password =""
    ClientId ="core-data"
    # Connection information
    Qos          =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive    =  "10" # Seconds (must be 2 or greater)
    Retained     = "false"
    AutoReconnect  = "true"
    ConnectTimeout = "5" # Seconds
    # TLS configuration - Only used if Cert/Key file or Cert/Key PEMblock are specified
    SkipCertVerify = "false"

[SecretStore]
Host = 'localhost'
Port = 8200
Path = '/v1/secret/edgex/coredata/'
Protocol = 'https'
RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
ServerName = 'localhost'
TokenFile = '/vault/config/assets/resp-init.json'
# Number of attemtps to retry retrieving secrets before failing to start the service.
AdditionalRetryAttempts = 10
# Amount of time to wait before attempting another retry
RetryWaitPeriod = "1s"
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

[Startup]
Duration = 30
Interval = 1
