Applicationname = 'core-data'
Consulprofilesactive = 'go'
Readmaxlimit = 100
Metadatacheck = false
Validatecheck = false
Addtoeventqueue = true
Persistdata = true
HeartBeatTime = 300000
HeartBeatMsg = 'Core data heart beat'
AppOpenMsg = 'This is the Core Data Micro Service'
Formatspecifier = '%(\\d=\\$)?([-#= 0(\\<]*)?(\\d=)?(\\.\\d=)?([tT])?([a-zA-Z%])'
Msgpubtype = 'zero'
Serverport = 48080
Serviceaddress= 'localhost'
ServiceName= 'core-data'
Deviceupdatelastconnected = false
Serviceupdatelastconnected = false
Datamongodbusername = 'core'
Datamongodbpassword = 'password'
Datamongodbdatabase = 'coredata'
Datamongodbhost = 'localhost'
Datamongodbport = 27017
DatamongodbsocketTimeout = 60000
DatamongodbmaxWaitTime = 120000
DatamongodbsocketKeepAlive = true
Consulhost = 'localhost'
Consulcheckaddress = 'http://localhost:48080/api/v1/ping'
Consulport = 8500
Checkinterval = '10s'
EnableRemoteLogging = false
Loggingfile = './logs/edgex-core-data.log'
Loggingremoteurl = 'http://localhost:48061/api/v1/logs'
Metadbaddressableurl = 'http://localhost:48081/api/v1/addressable'
Metadbdeviceserviceurl = 'http://localhost:48081/api/v1/deviceservice'
Metadbdeviceprofileurl = 'http://localhost:48081/api/v1/deviceprofile'
Metadbdeviceurl = 'http://localhost:48081/api/v1/device'
Metadbdevicereporturl = 'http://localhost:48081/api/v1/devicereport'
Metadbcommandurl = 'http://localhost:48081/api/v1/command'
Metadbeventurl = 'http://localhost:48081/api/v1/event'
Metadbscheduleurl = 'http://localhost:48081/api/v1/schedule'
Metadbprovisionwatcherurl = 'http://localhost:48081/api/v1/provisionwatcher'
Metadbpingurl = 'http://localhost:48081/api/v1/ping'
Activemqbroker = 'tcp://localhost:61616'
Zeromqaddressport = 'tcp://*:5563'
Amqbroker = 'tcp://localhost:0'
