[Writable]
DeviceUpdateLastConnected = false
MetaDataCheck = false
PersistData = true
ServiceUpdateLastConnected = false
ValidateCheck = false
LogLevel = 'INFO'
ChecksumAlgo = 'xxHash'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48080
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Core Data Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-core-data.log'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'coredata'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[MessageQueue]
Protocol = 'tcp'
Host = '*'
Port = 5563
Type = 'zero'
Topic = 'events'

[Secrets]
Host = '127.0.0.1'
Port = 8200
Path = '/v1/secret/data/edgex/coredata'
Protocol = "http"
 [Secrets.Authentication]
 AuthType = 'X-Vault-Token'
 AuthToken = 'roots'
