[Writable]
DeviceUpdateLastConnected = false
MetaDataCheck = false
PersistData = true
ServiceUpdateLastConnected = false
ValidateCheck = false
LogLevel = 'INFO'
ChecksumAlgo = 'xxHash'
   [Writable.InsecureSecrets]
      [Writable.InsecureSecrets.DB]
         path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 59880
ServerBindAddr = '' # Leave blank so default to Host value unless different value is needed.
StartupMsg = 'This is the Core Data Microservice'
MaxResultCount = 50000
MaxRequestSize = 0 # Not curently used.
RequestTimeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.core-metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 59881

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'coredata'
  Port = 6379
  Timeout = 5000
  Type = 'redisdb'

[MessageQueue]
Protocol = 'redis'
Host = 'localhost'
Port = 6379
Type = 'redis'
AuthMode = 'usernamepassword'  # required for redis messagebus (secure or insecure).
SecretName = 'redisdb'
PublishTopicPrefix = 'edgex/events' # /<device-profile-name>/<device-name> will be added to this Publish Topic prefix
SubscribeEnabled = true
SubscribeTopic = "edgex/events/#"  # required for subscribing to Events from MessageBus
  [MessageQueue.Optional]
  # Default MQTT Specific options that need to be here to enable evnironment variable overrides of them
  # Client Identifiers
  ClientId ="core-data"
  # Connection information
  Qos          =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
  KeepAlive    =  "10" # Seconds (must be 2 or greater)
  Retained     = "false"
  AutoReconnect  = "true"
  ConnectTimeout = "5" # Seconds
  # TLS configuration - Only used if Cert/Key file or Cert/Key PEMblock are specified
  SkipCertVerify = "false"

[SecretStore]
Type = 'vault'
Protocol = 'http'
Host = 'localhost'
Port = 8200
Path = '/v1/secret/edgex/core-data/'
TokenFile = '/tmp/edgex/secrets/core-data/secrets-token.json'
RootCaCertPath = ''
ServerName = ''
# Number of attempts to retry retrieving secrets before failing to start the service.
AdditionalRetryAttempts = 10
# Amount of time to wait before attempting another retry
RetryWaitPeriod = "1s"
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
