[Writable]
DeviceUpdateLastConnected = false
MetaDataCheck = false
PersistData = true
ServiceUpdateLastConnected = false
ValidateCheck = false

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48080
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the Core Data Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-core-data.log'
Level = 'INFO'

[Clients]
  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'coredata'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[MessageQueue]
Protocol = 'tcp'
Host = '*'
Port = 5563
Type = 'zero'


