ConfigPath = './config'
GlobalPrefix = 'config'
IsReset = true
FailLimit = 30
FailWaitTime = 3
AcceptablePropertyExtensions = ['.toml','.yaml', '.yml', '.properties']
YamlExtensions = ['.yaml','.yml']
TomlExtensions = ['.toml']
EnableRemoteLogging = false
LoggingFile = '/edgex/logs/edgex-config-seed.log'
LoggingRemoteURL = 'http://edgex-support-logging:48061/api/v1/logs'
LoggingLevel = 'INFO'

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'