Hostname = 'edgex-support-logging'
Port = 48061
Persistence = 'mongodb'
LoggingFile = '/edgex/logs/edgex-support-logging.log'
MongoDB = 'logging'
MongoCollection = 'logEntry'
MongoURL = 'edgex-mongo'
MongoPort = 27017
MongoConnectTimeout = 5000
SocketTimeout = 5000
MongoUsername = 'logging'
MongoPassword = 'password'
CheckInterval = '10s'
ConsulHost = 'edgex-core-consul'
ConsulPort = 8500
ConsulProfilesActive = 'docker;go'
