[Writable]
MarkPushed = false
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-export-distro'
Port = 48070
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Export Distro Microservice'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = true
File = '/edgex/logs/edgex-export-distro.log'

[Clients]
  [Clients.Export]
  Protocol = 'http'
  Host = 'edgex-export-client'
  Port = 48071

  [Clients.Logging]
  Protocol = 'http'
  Host = 'edgex-support-logging'
  Port = 48061

  [Clients.CoreData]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

[Certificates]
  [Certificates.MQTTS]
  Cert = 'dummy.crt'
  Key = 'dummy.key'

  [Certificates.AWS]
  Cert = 'dummy.crt'
  Key = 'dummy.key'

[MessageQueue]
Protocol = 'tcp'
Host = 'edgex-core-data'
Port = 5563
Type = 'zero'
Topic = 'events'

[AnalyticsQueue]
Protocol = 'tcp'
Host = '*'
Port = 5566
Type = 'zero'

[SecretStore]
Host = 'edgex-vault'
Port = 8200
Path = '/v1/secrets/edgex/export-distro/'
Protocol = 'http'
RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
ServerName = 'edgex-vault'
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
  AuthToken= 'edgex'

[Startup]
Duration = 30
Interval = 1
